### ISSUE TITLE
Implementazione logiche lato client

### ISSUE THREAD

**Issue by Fmarro** [SamueleM21/kezzapp-gruppo-2#2]
Implementazione logiche lato client

**Comment by Matteosalvatori4** [comment]
Implementata logica client con commit 924e33ca91848520254abcd99ed705833d11fb73, risolvere problema di trascrizione su db.

**Comment by Fmarro** [comment]
risolto bug registrazione con commit: 8b024aaf512f35c9e45459a55463af9787cad832

**Comment by SamueleM21** [comment]
chiuso con commit: 096e0666cf82b9da1efbda78d24b3e24f31839f4
